services:
  kowl:
    image: ${IMAGE_NAME:-quay.io/cloudhut/kowl}:${IMAGE_TAG:-master}
    environment:
      SERVER_LISTENPORT:
      KAFKA_BROKERS:
      KAFKA_SCHEMAREGISTRY_ENABLED:
      KAFKA_SCHEMAREGISTRY_URLS:
      CONNECT_ENABLED:
      CONNECT_CLUSTERS_NAME:
      CONNECT_CLUSTERS_URL:
    networks:
      kafka-net:
      traefik-net:
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-30s}
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:${TRAEFIK_SUBDOMAIN:-kowl}.${PUBLIC_HOSTNAME}
        traefik.backend: kowl
        traefik.port: '${SERVER_LISTENPORT}'
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
